# Generated by Django 3.2 on 2021-09-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='static/images/sample_user.jpg', upload_to='static/profiles_pic'),
        ),
    ]
